version: '3'

services:

  nginx:
    image: ${ECR_REGISTRY}/url-shortner-nginx
    build:
      context: .
      dockerfile: .docker/dockerfile
    links:
      - node1:node1
    depends_on:
      - node1
    ports:
      - "80:80"
    networks:
      - app-network
#    logging:
#      driver: awslogs
#      options:
#        awslogs-group: url-shortner-nginx
#        awslogs-region: ap-northeast-2
#        awslogs-stream-prefix: ecs

  node1:
    image: ${ECR_REGISTRY}/url-shortner-node1
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    volumes: [".:/usr/src/app"]
    environment:
      - INSTANCE=node1
    ports:
      - "3000:3000"
    networks:
      - app-network
#    logging:
#      driver: awslogs
#      options:
#        awslogs-group: url-shortner-nuxt
#        awslogs-region: ap-northeast-2
#        awslogs-stream-prefix: ecs

networks:
  app-network:
    driver: bridge
