version: '3'

services:

  nginx:
    image: ${ECR_REGISTRY}/url-shortner-nginx
    build:
      context: .
      dockerfile: .docker/dockerfile
    links:
      - node1:node1
      - node2:node2
      - node3:node3
    depends_on:
      - node1
      - node2
      - node3
    ports:
      - "80:80"
    networks:
      - app-network

  node1:
    image: ${ECR_REGISTRY}/url-shortner-node1
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    environment:
      - INSTANCE=node1
    networks:
      - app-network

  node2:
    image: ${ECR_REGISTRY}/url-shortner-node2
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    environment:
      - INSTANCE=node2
    networks:
      - app-network

  node3:
    image: ${ECR_REGISTRY}/url-shortner-node3
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    environment:
      - INSTANCE=node3
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
